import Image from 'next/image'
import React from 'react'

export const metadata = {
    title: "About Us",
    description: "Generated by create REDVision Technologies.",
    author: "REDVision Technologies Pvt. Ltd.",
};

const Products = () => {
    return (
        <section className="lg:px-40 md:px-20 px-6 my-10">
            <div className='my-5 text-center'>
                <h1 className="mb-4 text-3xl font-extrabold text-gray-900 dark:text-white md:text-5xl lg:text-6xl"><span className="text-transparent bg-clip-text bg-gradient-to-r to-red-500 from-blue-600">Product</span></h1>
            </div>
            <h1 className="text-xl font-bold tracking-tight leading-none md:text-5xl lg:text-xl text-center text-gray-700">
                Depending on your risk profile, investment horizon and personal preference, we at SELECT Financial Services offer various products that include the following
            </h1>
            <div className="gap-1 my-10 px-5 md:px-29">
                <div className="text-start bg-gray-100 shadow-lg rounded p-3 mb-5">
                    <h1 className="text-xl font-bold tracking-tight leading-none md:text-xl lg:text-xl uppercase text-gray-800">
                        Mutual Funds
                    </h1>
                    <p className="text-md font-normal text-gray-600">
                        To invest into Equity, Debt or Hybrid Mutual Fund schemes in lump sum or systematically.
                    </p>
                </div>
                <div className="text-start bg-gray-100 shadow-lg rounded p-3 mb-5">
                    <h1 className="text-xl font-bold tracking-tight leading-none md:text-xl lg:text-xl uppercase text-gray-800">
                        Stocks
                    </h1>
                    <p className="text-md font-normal text-gray-600">
                        To invest into direct equity, derivatives or pre-researched basket of stocks using best of technology!
                    </p>
                </div>
                <div className="text-start bg-gray-100 shadow-lg rounded p-3 mb-5">
                    <h1 className="text-xl font-bold tracking-tight leading-none md:text-xl lg:text-xl uppercase text-gray-800">
                        Insurance
                    </h1>
                    <p className="text-md font-normal text-gray-600">
                        Plans including Term, Health, Motor, Personal Accident, Critical Illness, Endowment, ULIP etc.
                    </p>
                </div>
                <div className="text-start bg-gray-100 shadow-lg rounded p-3 mb-5">
                    <h1 className="text-xl font-bold tracking-tight leading-none md:text-xl lg:text-xl uppercase text-gray-800">
                        FD & Bonds
                    </h1>
                    <p className="text-md font-normal text-gray-600">
                        Multiple options of secondary bonds and well rated Corporate Fixed Deposits of different tenures.
                    </p>
                </div>
                <div className="text-start bg-gray-100 shadow-lg rounded p-3 mb-5">
                    <h1 className="text-xl font-bold tracking-tight leading-none md:text-xl lg:text-xl uppercase text-gray-800">
                        PMS
                    </h1>
                    <p className="text-md font-normal text-gray-600">
                        Professionally managed portfolios depending on investors risk appetite and returns expectation.
                    </p>
                </div>
                <div className="text-start bg-gray-100 shadow-lg rounded p-3 mb-5">
                    <h1 className="text-xl font-bold tracking-tight leading-none md:text-xl lg:text-xl uppercase text-gray-800">
                        AIF
                    </h1>
                    <p className="text-md font-normal text-gray-600">
                        Pooled Investments made in venture capital, private equity, hedge funds, long short strategies etc.
                    </p>
                </div>
                <div className="text-start bg-gray-100 shadow-lg rounded p-3 mb-5">
                    <h1 className="text-xl font-bold tracking-tight leading-none md:text-xl lg:text-xl uppercase text-gray-800">
                        Small Case
                    </h1>
                    <p className="text-md font-normal text-gray-600">
                        Professionally curated basket of Stocks designed to build diversified, low cost & long term portfolio.
                    </p>
                </div>
                <div className="text-start bg-gray-100 shadow-lg rounded p-3 mb-5">
                    <h1 className="text-xl font-bold tracking-tight leading-none md:text-xl lg:text-xl uppercase text-gray-800">
                        Liqui Loans
                    </h1>
                    <p className="text-md font-normal text-gray-600">
                        P2P platform that provides lucrative investment opportunity with high diversification and low risk.
                    </p>
                </div>
            </div>
        </section>
    )
}

export default Products;